version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_BASE=/api
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=1
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    # Si corres un backend local en otro servicio, añade aquí depende y red
    depends_on:
      - backend
  backend:
    build:
      context: ./deploy/mock-backend
    command: node server.js
    ports:
      - "8081:8080"
volumes:
  node_modules:
